export const TITLE_LAYOUT = 'Phân loại Layout'
export const TITLE_KEYCAP = 'Phân loại Keycap'
export const TITLE_SWITCH = 'Phân loại Switch'
export const TITLE_PRICE = 'Giá sản phẩm'
export const TITLE_TRADEMARK = 'Thương hiệu'
export const TITLE_CATEGORY = 'Loại'
